### PR TITLE
change "pydea" to "pyDEA"

### PR DESCRIPTION
**Pull request by AlanFirmiano**
currently does not work with "pydea"

### CODE REVIEW

**Comment by jzuccollo** [comment]
Hey, thanks for the pull request but [pyDEA on PyPI](https://pypi.org/project/pyDEA/) is completely separate from this project and is not related.

**Comment by fcpetersen** [comment]
Hi! Where can I find pydea.zip to download?

**Comment by jzuccollo** [comment]
There isn't a built zip of this project but you probable want pyDEA on PyPI anyway. See my comment above.

**Comment by fcpetersen** [comment]
In fact, I would like to find  deapy.zip.

**Comment by jzuccollo** [comment]
Not sure exactly what you're asking for, sorry. If you want a build of this project then feel free to clone and build it locally.

**Comment by fcpetersen** [comment]
Screenshot_20211014-070959

**Comment by fcpetersen** [comment]
I am talking about this file: deapy zip

**Comment by jzuccollo** [comment]
That's a different project entirely and there is no equivalent zip file for this project.

**Pull request closed without merging**
